#! /usr/bin/perl

use File::Copy;

sub readprops($)
{
	my ($file) = @_;

	my %property;
	open(PROP,$file);
	while (<PROP>)
	{
		chop;
		if (m/^([^#].*?)=(.*)$/)
		{
			$property{$1}=$2;
		}
	}
	close(PROP);
	return %property;
}

sub compile($$$%)
{
	my ($roast, $revision, $release, $extprops) = @_;

	$props="";
	$logger="";
	if (exists $$extprops{'branch'})
	{
		$$extprops{'branchname'}=$$extprops{'name'}.'-'.$$extprops{'branch'};
	}
	else
	{
		$$extprops{'branchname'}=$$extprops{'name'};
	}
	$props.=" -Droast=$roast";
	$props.=" -Dproperties=../ant.properties";
	if ($release)
	{
		$props.=" -Doutputdir=".$options{'releasedir'}."/".$$extprops{'name'};
		$props.=" -Drelease=true";
	}
	else
	{
		$props.=" -Doutputdir=".$options{'outputdir'}."/".$$extprops{'branchname'};
		$props.=" -Dextension.revision=rev$revision";
		$logger.=" -logger org.apache.tools.ant.listener.MailLogger";
	}
	$result=system "ant -v".$props.$logger." -f build/build.xml clean-package >/dev/null 2>/dev/null";
	if (!$result)
	{
		print "build successful.\n";
		if ($release==0)
		{
			system "svn log --xml --limit 10 >".$options{"outputdir"}."/".$$extprops{'branchname'}."/".$$extprops{'name'}.".log";
			$source=$options{"outputdir"}."/".$$extprops{'branchname'}."/".$$extprops{'name'}.".xpi";
			$target=$options{'revisiondir'}."/".$$extprops{'branchname'}."/".$$extprops{'name'}."-".$$extprops{'version'}.".rev".$revision.".xpi";
			copy($source,$target);
		}
		return 1;
	}
	else
	{
		print "build failed.\n";
		return 0;
	}
}

sub outputinfo($$%)
{
	my ($roast, $revision, $extprops) = @_;

	open(INFO,">".$options{"outputdir"}."/".$$extprops{'branchname'}."/".$$extprops{'branchname'}.".properties");
	print INFO "name=".$$extprops{'name'}."\n";
	print INFO "version=".$$extprops{'version'}."\n";
	print INFO "revision=".$revision."\n";
	if (exists $$extprops{'branch'})
	{
		print INFO "branch=".$$extprops{'branch'}."\n";
	}
	close(INFO);
}

sub roast($$$)
{
	my ($roast,$revision,$release) = @_;

	print "Roasting $roast...";
	chdir $roast;
	
	my $svn="";
	$svn = qx/svn cleanup/;
	$svn = qx/svn cleanup build/;
	if ($revision)
	{
		$svn = qx/svn update -r $revision/;
	}
	else
	{
		$svn = qx/svn update/;
	}
	my %extprops = readprops("extension.properties");
	if ($svn =~ m/Updated to revision (\d+)\./)
	{
		print "updating to revision $1...";
		if ((compile($roast,$1,$release,\%extprops))&&(!$release))
		{
			outputinfo($roast,$1,\%extprops);
		}
	}
	elsif (($svn =~ m/At revision (\d+)\./)&&($force==1))
	{
		print "rebuilding from revision $1...";
		if ((compile($roast,$1,$release,\%extprops))&&(!$release))
		{
			outputinfo($roast,$1,\%extprops);
		}
	}
	else
	{
		print "up to date.\n";
	}
	chdir "..";
}

%options=readprops("roaster.properties");

chdir $options{'roastdir'};

mkdir "roast.lock" or die "Could not obtain lock.";

$force=0;
$revision=0;
$release=0;
for ($pos=0; $pos<=$#ARGV; $pos++)
{
	$arg=$ARGV[$pos];
	if (($arg eq "-f")||($arg eq "--force"))
	{
		$force=1;
	}
	elsif ($arg eq "-r")
	{
		$pos++;
		$revision=$ARGV[$pos];
	}
	elsif ($arg eq "-release")
	{
		$force=1;
		$release=1;
	}
	elsif (-d $arg)
	{
		$roasts[$#roasts+1]=$arg;
	}
	else
	{
		print "Invalid command line argument: $arg\n";
		exit;
	}
}

if ($#roasts>=0)
{
	for ($pos=0; $pos<=$#roasts; $pos++)
	{
		roast($roasts[$pos],$revision,$release);
	}
}
else
{
	opendir(ROASTS,".");
	while ($roast=readdir(ROASTS))
	{
		if ((-d $roast)&& !($roast =~ m/^\./)&&($roast ne "roast.lock"))
		{
			roast($roast,$revision,$release);
		}
	}
}

rmdir "roast.lock";
